In [1]:
#Question-1
import numpy as np
a=np.arange(2,50,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [4]:
#Qusetion-2
import numpy as np
lst1=[]
print("Enter your 1st list numbers:")
for i in range(5):
    a=int(input())
    lst1.append(a)
a1=np.array(lst1)
lst2=[]
print("Enter your 2nd list numbers:")
for i in range(5):
    b=int(input())
    lst2.append(b)
a2=np.array(lst2)
c=np.concatenate([a1, a2])
print("Concatination:\n",c)
d=np.sort(c)
print("sorted array:\n",d)


Enter your 1st list numbers:
3
8
24
1
659
Enter your 2nd list numbers:
70536
23
2
12
435
Concatination:
 [    3     8    24     1   659 70536    23     2    12   435]
sorted array:
 [    1     2     3     8    12    23    24   435   659 70536]


In [6]:
#Question-3
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(a)
print("dimensions of the given array is: ", a.ndim)
print("Size of given array is: ", a.size)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
dimensions of the given array is:  2
Size of given array is:  15


In [7]:
#question-4
arr = np. array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np. reshape(arr, (2, 5))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
#Question-5
import numpy as np
a = np.array([[11, 12],
              [13, 14]])
b = np.array([[25, 36],
              [77, 48]])
print("Verical stacking")
print(np.vstack((a, b)))
print()
print("Horizontal stacking")
print(np.hstack((a, b)))

Verical stacking1
[[11 12]
 [13 14]
 [25 36]
 [77 48]]

Horizontal stacking
[[11 12 25 36]
 [13 14 77 48]]
